# Generated by Django 2.0.5 on 2018-07-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('store_url', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
    ]
